services:
  docker_emby_system:
    image: emby/embyserver:4.9.0.23
    privileged: true
    container_name: docker_emby_system
    hostname: "MediaServerCenter"
    #    network_mode: host # Enable DLNA and Wake-on-Lan
    environment:
      # 你的用户id是多少就是多少uid=1000(qiuchenly) gid=1000(qiuchenly) groups=1000(qiuchenly) 直接写就是了
      - TZ=Asia/Shanghai
      - UID=1000 # The UID to run emby as (default: 2)
      - GID=100 # The GID to run emby as (default 2)
      - PUID=1000
      - PGID=100
      - GIDLIST=1000 # A comma-separated list of additional GIDs to run emby as (default: 2)
    extra_hosts:
      - "thetvdb.com:65.8.170.107"
      - 'api4.thetvdb.com:65.8.161.129'
      - 'api4.thetvdb.com:65.8.161.105'
      - 'api4.thetvdb.com:65.8.161.49'
      - 'api4.thetvdb.com:65.8.161.38'
      - 'api.themoviedb.org:65.8.161.111'
      - 'api.themoviedb.org:65.8.161.126'
      - 'api.themoviedb.org:65.8.161.83'
      - 'api.themoviedb.org:65.8.161.37'
      - 'image.tmdb.org:143.244.50.87'
      - 'artworks.thetvdb.com:99.84.234.115'
      - 'musicbrainz.emby.tv:23.239.10.174'
      - 'www.theaudiodb.com:104.21.57.210'
      - 'www.theaudiodb.com:172.67.149.243'
      - 'webservice.fanart.tv:51.89.210.79'
      - 'www.theaudiodb.com:172.67.149.243'
      - 'www.theaudiodb.com:104.21.57.210'
    volumes:
      - emby-config:/config # Configuration directory
      - /Volumes/data:/ExternalDisk
      - ./apploader.js:/system/dashboard-ui/apploader.js
      - ./Emby.Server.Implementations.dll:/system/Emby.Server.Implementations.dll
    devices:
      # 让宿主机显卡可以被调用 否则没有硬件解码器 chmod -R 777 /dev/dri
      - /dev/dri:/dev/dri # VAAPI/NVDEC/NVENC render nodes
    ports:
      - "8096:8096"
        # HTTP port
        #- "8920:8920" # HTTPS port
    restart: always

volumes:
  emby-config:

